#!/bin/sh
if [ $# -ne 1 ]; then
   echo "  Usage: buildman commandname"
   echo "  The result is in file r1.html"
   exit 1
fi
cat -  > temp$$ <<wrapper
<!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook V4.1//EN" [
  <!ENTITY replstart "&lt;">
  <!ENTITY replend   "&gt;">
  <!ENTITY repeatst   "{">
  <!ENTITY repeaten   "}">
  <!ENTITY quot CDATA  "&#22;">
  <!ENTITY refentrypage SYSTEM "$1.refentry">
 ]>
<article>
&refentrypage;
</article>
wrapper
docbook2man temp$$ 
rm temp$$
