ifndef  NITROS9DIR
NITROS9DIR      = $(HOME)/nitros9
endif
include $(NITROS9DIR)/rules.mak
include ../../coco3/cmds/makefile_common
AFLAGS          += -e -aH6309=1
LFLAGS		+= -l=$(NITROS9DIR)/lib/sys6309l2.l
