#!/bin/sh -e

NAME=$1
TAG=$2

HTDOCS=/home/project-web/nitros9/htdocs

if [ -z "$TAG" ]; then
	echo "$0: Missing name and date tag"
	exit 1
fi

cd $HTDOCS
mkdir latest-$TAG
cd latest-$TAG
unzip -o ../$NAME-$TAG.zip
echo "Options +Indexes" > .htaccess

cd $HTDOCS
rm latest
ln -s latest-$TAG latest
rm $NAME.zip
ln -s $NAME-$TAG.zip $NAME.zip
