#!/usr/bin/perl
# Makes 'bootlist' and 'bootfile' in the current directory for NitrOS-9 Level 2
$NITROS9DIR = $ENV{'NITROS9DIR'};
$CLOUD9DIR = $ENV{'CLOUD9DIR'};

if (@ARGV[0] == '')
{
	$DISTRO = "6809l2";
}
else
{
	$DISTRO = @ARGV[0]."l2";
}

$md="$NITROS9DIR/$DISTRO/modules";
$sd="$CLOUD9DIR/Products/SuperDrivers/software/$DISTRO";
$dd="$CLOUD9DIR/Products/DriveWire/software/$DISTRO";

@tracklist_dw=(
	"$md/rel_80",
	"$dd/boot_dw",
	"$md/krn");

# DriveWire Boot with /X0 as /DD
@bootlist_dw=(
	"$md/krnp2",
	"$md/ioman",
	"$md/init",
	"$md/rbf.mn",
	"$dd/drivewire.dr",
	"$dd/ddx0.dd",
	"$dd/x1.dd",
	"$dd/x2.dd",
	"$dd/x3.dd",
	"$md/rb1773.dr",
	"$md/d0_80d.dd",
	"$md/d1_40d.dd",
	"$md/scf.mn",
	"$md/cc3io.dr",
	"$md/term_win80.dt",
	"$md/keydrv_cc3.sb",
	"$md/joydrv_joy.sb",
	"$md/snddrv_cc3.sb",
	"$md/grfint.io",
	"$md/w.dw",
	"$md/w1.dw",
	"$md/w2.dw",
	"$md/w3.dw",
	"$md/w4.dw",
	"$md/w5.dw",
	"$md/w6.dw",
	"$md/w7.dw",
	"$md/sc6551.dr",
	"$md/t2_sc6551.dd",
	"$md/t3_sc6551.dd",
	"$md/pipeman.mn",
	"$md/piper.dr",
	"$md/pipe.dd",
	"$md/clock_60hz",
	"$md/clock2_cloud9");

#                $(C9)/Products/SuperDrivers/software/$DISTRO/lldw.dr \
#                $(C9)/Products/SuperDrivers/software/$DISTRO/ddx0.dd \
#                $(C9)/Products/SuperDrivers/software/$DISTRO/x1.dd \
#                $(C9)/Products/SuperDrivers/software/$DISTRO/x2.dd \
#                $(C9)/Products/SuperDrivers/software/$DISTRO/x3.dd \



# Select our bootlist and tracklist
@bootlist = @bootlist_dw;
@tracklist = @tracklist_dw;

# Create the files
if (-e "bootfile")
{
	system("rm bootfile");
}

foreach $file (@bootlist)
{
	printf("cat $file>>bootfile\n");
	system("cat $file>>bootfile");
}

if (-e "boottrack")
{
	system("rm boottrack");
}

foreach $file (@tracklist)
{
	printf("cat $file>>boottrack\n");
	system("cat $file>>boottrack");
}
