#!/usr/bin/perl
# Makes 'bootlist' and 'bootfile' in the current directory for NitrOS-9 Level 2
$NITROS9DIR = $ENV{'NITROS9DIR'};
$CLOUD9DIR = $ENV{'CLOUD9DIR'};

if (@ARGV[0] == '')
{
	$DISTRO = "6809l1";
}
else
{
	$DISTRO = @ARGV[0]."l1";
}

$md="$NITROS9DIR/$DISTRO/modules";
$sd="$CLOUD9DIR/Products/SuperDrivers/software/$DISTRO";
$dd="$CLOUD9DIR/Products/DriveWire/software/$DISTRO";

@tracklist_ide=(
	"$md/rel",
	"$md/krn",
	"$md/krnp2",
	"$md/init",
	"$sd/boot_ide");

# IDE Boot with IDE Master as /DD
@bootlist_ide=("$md/ioman",
	"$md/rbf.mn",
	"$sd/rbsuper.dr",
	"$sd/llide.dr",
	"$sd/lltc3.dr",
	"$sd/dd_ide.dd",
	"$sd/i0_ide.dd",
	"$sd/i1_ide.dd",
	"$sd/ih_ide.dd",
	"$sd/s0_tc3.dd",
	"$sd/s1_tc3.dd",
	"$sd/s2_tc3.dd",
	"$sd/s3_tc3.dd",
	"$sd/s4_tc3.dd",
	"$sd/s5_tc3.dd",
	"$sd/s6_tc3.dd",
	"$sd/s7_tc3.dd",
	"$sd/sh_tc3.dd",
	"$md/rb1773.dr",
	"$md/d0_80d.dd",
	"$md/d1_40d.dd",
	"$md/scf.mn",
	"$md/ccio.dr",
	"$md/co32.io",
	"$md/term32.dt",
	"$md/sc6551.dr",
	"$md/t2_sc6551.dd",
	"$md/t3_sc6551.dd",
	"$md/pipeman.mn",
	"$md/piper.dr",
	"$md/pipe.dd",
	"$md/clock_60hz",
	"$md/clock2_cloud9",
	"$md/sysgo_dd");


# Select our bootlist and tracklist
@bootlist = @bootlist_ide;
@tracklist = @tracklist_ide;

# Create the files
if (-e "bootfile")
{
	system("rm bootfile");
}

foreach $file (@bootlist)
{
	printf("cat $file>>bootfile\n");
	system("cat $file>>bootfile");
}

if (-e "boottrack")
{
	system("rm boottrack");
}

foreach $file (@tracklist)
{
	printf("cat $file>>boottrack\n");
	system("cat $file>>boottrack");
}
