include ../rules.mak

all:
	$(CD) basic09; make
	$(CD) ccguide; make
	$(CD) os9guide; make
	$(CD) os9sysprog; make

clean:
	$(CD) basic09; make clean
	$(CD) ccguide; make clean
	$(CD) os9guide; make clean
	$(CD) os9sysprog; make clean
