pdf: articles.pdf

articles.pdf: articles.docbook bootprocess.article ded.article diskcrash.article \
            os9software.article tutorial.article extensionmodule.article
	docbook2pdf articles.docbook
